AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Aurora Stress Test

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        AWS_CODEGURU_PROFILER_GROUP_ARN: arn:aws:codeguru-profiler:eu-west-1:952137551633:profilingGroup/aws-aurora-stress-test

Resources:
  StressTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Tracing: Active
      Policies: AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-04653030
        SubnetIds:
          - subnet-a1ceb4af
          - subnet-f77afa91
          - subnet-68f47a49
          - subnet-efcb47b0
          - subnet-45045708
          - subnet-79cb1c48
      Events:
        StressTest:
          Type: Api
          Properties:
            Path: /stressit
            Method: get

Outputs:
  StressTestApi:
    Description: "API Gateway endpoint URL for Prod stage for Stress Test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stressit/"
